### ISSUE TITLE
Refresh Naxos from source to remove otherType

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-metadata/metadata-remediation#23]
10135879

**Comment by arcadiafalcone** [comment]
https://argo.stanford.edu/catalog?f%5Bproject_tag_ssim%5D%5B%5D=Naxos+%3A+born+digital+audio
nq067qd2126 already refreshed
bg151tb4854 still original

**Comment by arcadiafalcone** [comment]
```
Before:
  Success: 2764
  Different: 765
After:
  Success: 3913
  Different: 43
```
